import crypto from 'crypto';
const transitions = { intake: ['validated'], validated: ['assigned', 'escalated'], assigned: ['draft_response', 'waiting', 'escalated'], draft_response: ['human_review', 'approved'], human_review: ['approved', 'draft_response', 'escalated'], approved: ['sent'], sent: ['waiting', 'resolved'], waiting: ['draft_response', 'resolved', 'escalated'], resolved: ['closed', 'recovered'], escalated: ['assigned', 'resolved'], recovered: ['assigned', 'resolved'], closed: [] };
const perms = { customer: ['read_self', 'reply'], agent: ['read', 'draft', 'send'], supervisor: ['read', 'draft', 'send', 'approve', 'escalate', 'assign'], admin: ['read', 'draft', 'send', 'approve', 'escalate', 'assign', 'configure'] };
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.keys(v).sort().reduce((out,key)=>{out[key]=canonical(v[key]);return out;},{}):v;
export const hash = v => crypto.createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
export function requireScope(actor, tenantId, customerId, action) { if (!actor || actor.tenantId !== tenantId) throw new Error('tenant_scope_denied'); if (actor.role === 'customer' && actor.subjectId !== customerId) throw new Error('subject_scope_denied'); if (!(perms[actor.role] || []).includes(action)) throw new Error('role_scope_denied'); }
export function validateCase(input) { for (const f of ['customerId', 'channel', 'subject', 'body', 'consent']) if (input[f] === undefined || input[f] === null || input[f] === '') throw new Error(`missing_${f}`);if(!['email','chat','sms','voice','web'].includes(input.channel))throw new Error('invalid_channel');if(typeof input.subject!=='string'||!input.subject.trim()||input.subject.length>500||typeof input.body!=='string'||!input.body.trim()||input.body.length>100000)throw new Error('invalid_case_content'); if (!input.consent.processing || !input.consent.purpose || !Number.isInteger(input.consent.retentionDays) || input.consent.retentionDays < 1 || input.consent.retentionDays > 3650) throw new Error('processing_consent_and_retention_required');const normalized={...input,customerId:String(input.customerId),subject:input.subject.trim(),body:input.body.trim(),ownerId:input.ownerId?String(input.ownerId):null}; return { ...normalized, caseHash: hash(normalized), state: 'validated' }; }
export function validateCallAnalysis(input) { for (const f of ['callId', 'recordingChecksum', 'transcript', 'consentId', 'modelVersion','providerReceiptId']) if (!input[f]) throw new Error(`missing_${f}`); if (!input.recordingConsent || !input.analysisConsent) throw new Error('call_consent_required');if(!/^[a-f0-9]{64}$/i.test(input.recordingChecksum))throw new Error('invalid_recording_checksum'); if (!Array.isArray(input.transcript.segments) || !input.transcript.segments.length || input.transcript.segments.some(s => !s.speaker || !s.text || !Number.isSafeInteger(s.startMs) || s.startMs < 0)) throw new Error('timestamped_transcript_required'); return { ...input, transcriptHash: hash(input.transcript), label: 'ADVISORY SENTIMENT — HUMAN REVIEW REQUIRED' }; }
export function transition(current, target, ctx = {}) { if (!(transitions[current] || []).includes(target)) throw new Error('invalid_transition'); if (target === 'assigned' && !ctx.ownerId) throw new Error('owner_required'); if (target === 'approved' && ctx.consequential && (!ctx.humanApprovalId || ctx.approverId === ctx.authorId)) throw new Error('independent_human_approval_required'); if (target === 'sent' && !ctx.providerReceiptId) throw new Error('provider_receipt_required'); return target; }
export function delivery(provider, operation, payload, idempotencyKey, receipt) { if (!provider || !operation || !idempotencyKey) throw new Error('typed_delivery_identity_required');if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('invalid_delivery_payload'); const payloadHash = hash(payload); if (receipt && receipt.payloadHash !== payloadHash) throw new Error('receipt_payload_mismatch'); return { provider, operation, payloadHash, idempotencyKey, state: receipt ? 'confirmed' : 'queued', receipt: receipt || null }; }
export function evaluate(result, limits) {const scores=['correctness','edgeCaseRecall','escalationRecall','resolutionRate','maxGroupDelta'];for(const name of scores)if(!Number.isFinite(result[name])||result[name]<0||result[name]>1)throw new Error(`invalid_${name}`);for(const name of ['correctness','edgeCaseRecall','resolutionRate','maxGroupDelta'])if(!Number.isFinite(limits[name])||limits[name]<0||limits[name]>1)throw new Error(`invalid_${name}_limit`);if(!Number.isFinite(result.latencyMs)||result.latencyMs<0||!Number.isFinite(limits.latencyMs)||limits.latencyMs<0)throw new Error('invalid_latency'); const failures = []; if (result.correctness < limits.correctness) failures.push('correctness'); if (result.edgeCaseRecall < limits.edgeCaseRecall) failures.push('edge_cases'); if (result.escalationRecall < 1) failures.push('escalation'); if (result.latencyMs > limits.latencyMs) failures.push('latency'); if (result.resolutionRate < limits.resolutionRate) failures.push('outcome'); if (result.maxGroupDelta > limits.maxGroupDelta) failures.push('bias'); return { accepted: !failures.length, failures, resultHash: hash({ result, limits }) }; }
